name: ci
on:
  push: { branches: [ main, master ] }
  pull_request: { branches: [ main, master ] }
jobs:
  lint-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint (ruff)
        run: |
          python -m pip install ruff
          ruff check .
      - name: Smoke run (help)
        run: |
          python clump_sfv_rework.py --help
          python halo_from_power_ST.py --help
          python abmatch_uvlf_from_power.py --help
